site_name: Erandi Estrada - MDEF & Fab Lab Barcelona
site_description: Master in Design for Emergent Futures
site_author: Erandi Estrada
copyright: Copyleft 2023 "Erandi Estrada" - GNU Free Documentation License
repo_url: 'https://github.com/erandi-estrada/MDEF-Portfolio'
site_url: https://erandi-estrada.github.io/MDEF-Portfolio/

nav:
  - Home: index.md  
  - Projects: projects/Portfolio.md
  - About: about/me.md

extra:
  social:
    - icon: fontawesome/brands/medium
      link: https://medium.com/
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/
    - icon: fontawesome/brands/linkedin
      link: "https://www.linkedin.com/in/"
    - icon: fontawesome/brands/github
      link: "https://github.com/"

theme:
  name: material
  palette:
    primary: blue
    accent: purple
  font:
    text: Be Vietnam
    code: Cutive Mono
  icon:
    logo: material/memory
  favicon: images/favicon.svg
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - admonition
  - pymdownx.details

extra_css:
  - stylesheets/extra.css